[package]
name = "puts"
version = "0.1.0"
authors = ["Charles Chamberlain <charlespipin@gmail.com>"]
readme = "README.md"
license = "LICENSE.txt"
description = "a macro puts! just puts!(2, object, 'h')"
documentation = "run tests with `cargo test -- --nocapture`"

[dependencies]
