[package]
name = "puts"
version = "0.1.1"
authors = ["Charles Chamberlain <charlespipin@gmail.com>"]
readme = "README.md"
license = "MIT"
description = "a macro puts! just puts!(2, object, 'h')"

[dependencies]
